const fallbackCreations = [
  {
    type: "portfolio",
    title: "Portfolioo",
    url: "https://prudhvi-kollana-portfolio.vercel.app/",
    label: "Personal Portfolio",
    description: "Central hub showcasing my work, timeline & achievements.",
    icon: "Grid",
    tags: ["About Me", "Showcase", "Resume"],
    image: "/images/portfolio.jpg",
    display: true,
    order: 1,
    is_hub: false,
    is_status: false,
  },
  {
    type: "emi-master",
    title: "EMIMaster",
    url: "https://emi-master.vercel.app/",
    label: "Finance Tool",
    description: "Advanced EMI calculator with real-time visual insights.",
    icon: "BarChart2",
    tags: ["Planning", "Loans", "Calculator"],
    image: "/images/emi-master.jpg",
    display: true,
    order: 2,
    is_hub: false,
    is_status: false,
  },
  {
    type: "housiee",
    title: "Housiee",
    url: "https://housiee.vercel.app/",
    label: "Game",
    description: "Interactive online housie game built for fun sessions.",
    icon: "Gamepad2",
    tags: ["Fun", "Party", "Multiplayer"],
    image: "/images/housiee.jpg",
    display: true,
    order: 3,
    is_hub: false,
    is_status: false,
  },
  {
    type: "tally",
    title: "Tally",
    url: "https://tally-play.vercel.app/",
    label: "Puzzle",
    description: "A mini interactive maths game built for casual brain play.",
    icon: "Cpu",
    tags: ["Focus", "Time-pass", "Prototype"],
    image: "/images/tally.jpg",
    display: true,
    order: 4,
    is_hub: false,
    is_status: false,
  },
  {
    type: "mini-score-board",
    title: "MiniScoreBoard",
    url: "https://my-score-board.vercel.app/",
    label: "Mini ScoreBoard",
    description:
      "A fast, lightweight score tracker for quick games, challenges, and friendly matches.",
    icon: "List",
    tags: ["Real-time", "Scorekeeping", "Game Tool"],
    image: "/images/mini-score-board.jpg",
    display: true,
    order: 5,
    is_hub: false,
    is_status: false,
  },
  {
    type: "score-dash-board",
    title: "ScoreDashBoard",
    url: "https://score-dash-board.vercel.app/",
    label: "Smart Dashboard",
    description:
      "A real-time game session dashboard to organize matches, generate AI teams or players, balance squads and track scores with live rankings and stats.",
    icon: "Monitor",
    tags: [
      "Live Scores",
      "AI Teams",
      "AI Players",
      "Team Balancing",
      "Leaderboard",
      "Multi-mode",
    ],
    image: "/images/score-dash-board.jpg",
    display: true,
    order: 6,
    is_hub: false,
    is_status: false,
  },
  {
    type: "spin-out",
    title: "SpinOut",
    url: "https://try-spinout.vercel.app/",
    label: "Party Game",
    description: "Truth or dare prompts for quick ice-breakers & parties.",
    icon: "Puzzle",
    tags: ["Engage", "Social", "Entertainment"],
    image: "/images/spin-out.jpg",
    display: true,
    order: 7,
    is_hub: false,
    is_status: false,
  },
  {
    type: "network-status-hub",
    title: "NetworkStatusHub",
    url: "https://network-status-hub.vercel.app/",
    label: "Live Status",
    description: "Real-time system health, uptime tracking and outage reports.",
    icon: "Activity",
    tags: ["Monitoring", "Incidents", "Operations"],
    image: "/images/network-status-hub.jpg",
    display: true,
    order: 8,
    is_hub: false,
    is_status: true,
  },
    {
    type: "portfolio-hub",
    title: "PortfolioHub",
    url: "https://prudhvi-kollana-portfolio-hub.vercel.app/",
    label: "Portfolio Hub",
    description: "Portfolio hub showcasing all creations.",
    icon: "Globe",
    tags: [
      "Showcase",
      "Hub"
    ],
    image: "/images/portfolio-hub.jpg",
    display: false,
    order: 9,
    is_hub: true,
    is_status: false,
  },
];

export default fallbackCreations;
